version: "3"
services:
  strapi:
    container_name: campus-backend
    build: .
    image: campus-backend:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-json.lock:/opt/package-json.lock
      - ./.env:/opt/app/.env
    ports:
      - "1337:1337"
    networks:
      - strapi
    # depends_on:
    #   - strapiDB

  # strapiDB:
  #   image: postgres:12.0-alpine
  #   container_name: strapi-db
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     POSTGRES_USER: lvallejos
  #     POSTGRES_PASSWORD: notSecureChangeMe2511
  #     POSTGRES_DB: campus-db
  #   volumes:
  #     - strapi-data:/var/lib/postgresql/data/ #using a volume
  #     #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - strapi

# volumes:
#     strapi-data:

networks:
  strapi:
    driver: bridge
